#' Read multiple CSV files and write a CSV file with the information combined from different years
#' with the selected columns
#' 
#' Read files specifying the columns as a regular expression and generate an output file with all
#' this information. Also, the rows are *randomized*.
#'
#' @param input_path path to the folder with the CSV files with the "raw" data
#' @param cols_regex regular expression to select the columns of the data
#' @param output_csv_path path of the CSV file to be generated by the function
#'
#' @return Tibble with the data sets from different years combined and with the columns selected
#' @export
#'
#' @examples

condense_different_years <- function(input_path, output_csv_path, cols_regex) {
  
  # list files for applicants
  files_applicants <- list.files(here(input_path), 
                                 full.names = TRUE, pattern = "postulantes[.]csv$")
  
  # read data sets selecting the column for specialty
  final_dat <- read_csv_by_cols(files_applicants, cols_regex)
  # randomize the order of rows
  i <- sample(seq_len(nrow(final_dat)))
  final_dat <- final_dat[i, ] %>% arrange(year)
  
  # write the data
  write_csv(final_dat, here(output_csv_path))
  return(final_dat)
  
}

