---
title: "Analysis"
author: "Daniel Medina-Neira"
date: "2021-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# set the project as the root directory
knitr::opts_knit$set(root.dir = here::here())
```

## Hypothesis and importance

- How are the numbers of females being accepted into specialties changing across the different specialties.
- Women are having more opportunities in different fields, and medicine is probably not an exception, this is important because, for example, during this COVID-19 pandemic men were disproportionately affected, just because of the sex. Having more (sex) diversity is positive in different ways and maybe that is something we are working towards to.

------------------------------------------------------------------------

# Title

## Introduction

Current situation: proportion of female doctors and females with specialties.

## Methods / results

### Women *entering/applying* specialties in different years

#### Total / accumulated

#### By specialties

#### By region

### Women *working* in specialties in different years

#### Total / accumulated

#### By specialties

#### By region


## Conclusion

## Discussion

COVID-19 argument: women play a crucial role in society and nowadays they are being an increasing force in some fields, and medicine is no exception. Having more women is a good thing, for example, at this time, during the COVID-19 pandemic, males were disproportionately affected just because of the sex and sometimes this could have a big impact in some places with low numbers of certain specialties. This is just an example, the presence of females could help in many different ways.

Specialists are NOT all the physicians, there are a lot of physicians that are not specialists (how many?)





